config/routes.rb
Rails.application.routes.draw do
  mount LetsencryptPlugin::Engine, at: '/'

  devise_for :members, controllers: {registrations: 'registrations'}
  root 'prototype#index'
  resources :service_forms, only: [:create]

  namespace :member do
    root 'members#social_services'
    get 'list' => 'members#index'
    resources :social_services, only: [:create, :destroy]
  end

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  as_enum :profession, [:designer, :developer, :marketing]

  mount_uploader :avatar, MemberAvatarUploader

  has_many :social_services, dependent: :destroy
end

app/models/service_form.rb
class ServiceForm < ActiveRecord::Base
  as_enum :project_type, [:website_development, :website_design, :identity_design, :marketing_strategies]
  as_enum :budget_range, %i(six_hundred_thousand one_million three_million five_million)
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/social_service.rb
class SocialService < ActiveRecord::Base
  belongs_to :member

  as_enum :service, [:email, :facebook, :github, :twitter, :dribbble, :behance, :'google+', :instagram, :lastfm, :linkedin, :medium, :self_hosted_blog, :tumblr, :wordpress, :youtube, :pinterest]
end

app/models/unknow_member.rb
class UnknowMember
  def name
    'unknow member'
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'member'

  before_action :authenticate_member!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  layout :layout_by_resource

  def current_member
    super || UnknowMember.new
  end

  private

  def layout_by_resource
    if devise_controller?
      "member"
    else
      "application"
    end
  end

  def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit(:name, :message, :avatar, :work_field, :profession,
          :email, :password, :password_confirmation)
      end
      devise_parameter_sanitizer.for(:account_update) do |u|
        u.permit(:name, :message, :avatar, :work_field, :profession,
          :email, :password, :password_confirmation, :current_password)
      end
    end
end

app/controllers/member/members_controller.rb
class Member::MembersController < AdminController
  def social_services
    get_member_services
    @new_sns = current_member.social_services.new
  end

  def index
    @members = Member.all
  end

  private

  def get_member_services
    @sns_list = []
    current_member.social_services.each do |service|
      @sns_list << service if service.id.present?
    end
  end
end

app/controllers/member/social_services_controller.rb
class Member::SocialServicesController < ApplicationController
  def create
    @service = current_member.social_services.new(service_params)
    if @service.save
      flash[:success] = "已經新增 #{@service.service}"
      redirect_to :back
    else
      flash[:error] = "請檢查欄位是否填妥"
      redirect_to :back
    end
  end

  def destroy
    @service = SocialService.find(params[:id])
    @service.destroy

    flash[:success] = "#{@service.service} 已經刪除"

    redirect_to :back
  end

  private

  def service_params
    params.require(:social_service).permit(:service, :link, :member_id)
  end
end

app/controllers/prototype_controller.rb
class PrototypeController < ApplicationController
  def index
    @form = ServiceForm.new
    @members = Member.includes(:social_services).all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    flash[:success] = 'Hello, 若想加入我們，歡迎您將送 Resume 到 hr@oddesign.expert'
    redirect_to root_path
  end

  def create
    flash[:success] = 'Hello, 若想加入我們，歡迎您將送 Resume 到 hr@oddesign.expert'
    redirect_to root_path
  end
end

app/controllers/service_forms_controller.rb
class ServiceFormsController < ApplicationController
  def create
    @form = ServiceForm.new(form_params)

    message = [
      "時間：#{Time.now.to_s}",
      "===============================================",
      "Email：#{@form[:email]}",
      "Name：#{@form[:name]}",
      "案件類型：#{@form.class.human_enum_name(:project_type, @form.public_send(:project_type))}",
      "預算範圍：#{@form.class.human_enum_name(:budget_range, @form.public_send(:budget_range))}",
      "其他敘述：\n#{@form[:description]}"
    ].join("\n\n")

    if @form.save
      SlackNotify.new(message: message, username: '案件需求通知', channel: '#customers-message')
      flash[:success] = '訊息已送出，將盡快與您聯絡。'
      redirect_to :back
    else
      flash[:error] = '請檢查欄位'
      redirect_to :back
    end
  end

  private

  def form_params
    params.require(:service_form).permit(:email, :name, :project_type, :budget_range, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_profession_icon(profession)
    case profession
    when :designer
      icon 'pencil', class: 'fa-2x'
    when :developer
      icon 'keyboard-o', class: 'fa-2x'
    when :marketing
      icon 'bar-chart', class: 'fa-2x'
    else
      icon 'heart', class: 'fa-2x'
    end
  end

  def render_member_avatar(member)
    return image_tag member.avatar, class: 'avatar' if member.avatar.present?
    image_placeholder width: 200, height: 200, text: 'no pic', class: 'avatar'
  end

  def render_member_sns_link(service)
    if service.service == :email
      mail_to service.link, class: 'social-icon' do
        render_social_icon(service.service)
      end
    else
      link_to service.link, class: 'social-icon', target: '_blank' do
        render_social_icon(service.service)
      end
    end
  end

  def render_social_icon(service)
    case service
    when :email
      icon 'envelope-o'
    when :facebook
      icon 'facebook-official'
    when :twitter
      icon 'twitter-square'
    when :github
      icon 'github'
    when :dribbble
      icon 'dribbble'
    when :behance
      icon 'behance'
    when :'google+'
      icon 'google-plus-square'
    when :instagram
      icon 'instagram'
    when :lastfm
      icon 'lastfm-square'
    when :linkedin
      icon 'linkedin'
    when :medium
      icon 'medium'
    when :pinterest
      icon 'pinterest'
    when :tumblr
      icon 'tumblr-square'
    when :wordpress
      icon 'wordpress'
    when :youtube
      icon 'youtube'
    when :self_hosted_blog
      icon 'rss-square'
    end
  end

  def navi_menu_actived?(args)
    path = args[:path]
    class_name = args[:class_name] || 'actived'
    return class_name if current_page?(path)
  end

  def image_placeholder(args)
    width = args[:width] || '300'
    height = args[:height] || '300'
    text = args[:text] || "#{width} x #{height}"
    classes = args[:class] || ""

    image_tag "http://placehold.it/#{width}x#{height}&text=#{text}", :class => "#{classes}"
  end
end

app/helpers/member/members_helper.rb
module Member::MembersHelper
end

app/helpers/member/social_services_helper.rb
module Member::SocialServicesHelper
end

app/helpers/service_forms_helper.rb
module ServiceFormsHelper
end

app/views/common/_footer.html.erb
<!-- footer -->
<footer>

</footer>

app/views/common/_header.html.erb
<!-- Dropdown Structure -->
<ul id="user-menu" class="dropdown-content">
  <li>
    <%= link_to root_path do %>
      <i class="material-icons left">home</i>回到前台
    <% end %>
  </li>
  <li>
    <%= link_to edit_member_registration_path do %>
      <i class="material-icons left">account_box</i>個人資料
    <% end %>
  </li>

  <li class="divider"></li>

  <li>
    <%= link_to destroy_member_session_path, method: 'delete' do %>
      <i class="material-icons left">exit_to_app</i>登出
    <% end %>
  </li>
</ul>

<!-- navigation bar -->
<nav>
  <div class="container">
    <div class="nav-wrapper">
      <span class="brand-logo">odd</span>
      <ul class="right hide-on-med-and-down">
        <li class="<%= navi_menu_actived?(path: member_root_path, class_name: 'active') %>">
          <%= link_to member_root_path do %>
            <i class="material-icons left">people</i>SNS 連結管理
          <% end %>
        </li>
        <li class="<%= navi_menu_actived?(path: member_list_path, class_name: 'active') %>">
          <%= link_to member_list_path do %>
            <i class="material-icons left">people</i>成員列表
          <% end %>
        </li>
        <!-- Dropdown Trigger -->
        <li><a class="dropdown-button" href="#!" data-activates="user-menu">Hi, <%= current_member.name %><i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
    </div>
  </div>
</nav>

<%= content_for :handwrite_js do %>
  <script>
    $(".dropdown-button").dropdown();
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Oracle Digital Design :: 神御數位設計 :: odd</title>
    <meta name="description" content="odd 深度剖析客戶需求與企業文化，針對需求不同提出最精準的解決方案，從品牌設計行銷、網站建置到手機 App 開發，全面幫助每個客戶提升品牌價值與利潤。">
    <meta name="viewport" content="width=device-width">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <%= growlyflash_static_notices %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'modernizr' %>

  </head>
  <body class='<%# "#{controller.controller_name}-#{controller.action_name}" %>'>
      <!--[if lt IE 7]>
          <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
      <![endif]-->

  <%# render :partial => 'common/header' %>

  <%= yield %>

  <%# render :partial => 'common/footer' %>



  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, 'data-turbolinks-eval' => true %>
  <%= yield :handwrite_js %>

  </body>
</html>

app/views/layouts/member.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Oracle Digital Design :: 神御數位設計 :: odd</title>
    <meta name="description" content="odd 深度剖析客戶需求與企業文化，針對需求不同提出最精準的解決方案，從品牌設計行銷、網站建置到手機 App 開發，全面幫助每個客戶提升品牌價值與利潤。">
    <meta name="viewport" content="width=device-width">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <%= growlyflash_static_notices %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'modernizr' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  </head>
  <body class='<%= "#{controller.controller_name}-#{controller.action_name} member-layout" %>'>
      <!--[if lt IE 7]>
          <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
      <![endif]-->

  <%= render partial: 'common/header' %>

  <%= yield %>

  <%# render :partial => 'common/footer' %>



  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, 'data-turbolinks-eval' => true %>
  <%= yield :handwrite_js %>

  </body>
</html>

app/views/member/members/index.html.erb
<div class="container">
  <h4 class="title">成員列表</h4>
  <table class="member-list hoverable">
    <thead>
      <tr>
          <th data-field="id">Name</th>
          <th data-field="name">工作領域</th>
          <th data-field="price">簡述</th>
          <th>選項</th>
      </tr>
    </thead>

    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= member.name %></td>
          <td><%= member.work_field %></td>
          <td><%= member.message %></td>
          <td>
            <a href="#" class="btn">向上移動</a>
            <a href="#" class="btn">向下移動</a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/member/members/social_services.html.erb
<div class="container">
  <h4 class="title">社群網站連結管理</h4>
  <a href="#new_social_service" class="btn green pull-right modal-trigger"><i class="material-icons left">add</i> 新增社群連結</a>
  <table class="member-list hoverable">
    <thead>
      <tr>
          <th data-field="id">SNS</th>
          <th data-field="name">Link</th>
          <th>選項</th>
      </tr>
    </thead>

    <tbody>
      <% @sns_list.each do |service| %>
        <tr>
          <td><span><%= service.service.to_s %></span></td>
          <td><%= link_to service.link, service.link %></td>
          <td>
            <%= link_to member_social_service_path(service),
              class: "btn red",
              method: :delete,
              :data => {confirm: "您確定要刪除 #{service.service}？",
                        :'confirm-button-text' => '確定刪除',
                        :'cancel-button-text' => '取消',
                        :'sweet-alert-type' => 'warning',
                        text: '這個動作將無法復原！'} do %>
              <i class="material-icons left">delete</i>刪除
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!-- new social service form -->
<div id="new_social_service" class="modal">
  <%= form_for [:member, @new_sns] do |f| %>
    <div class="modal-content">
      <h5 class="title">新增社群服務</h5>
        <div class="input-field">
          <%= select :social_service, :service, enum_option_pairs(SocialService, :service), prompt: '選擇想新增的社群服務' %>
          <%= f.label :service, '專業類別' %>
        </div>
        <div class="input-field">
          <%= f.text_field :link, placeholder: 'http://www.facebook.com/oresama_saikyou' %>
          <%= f.label :link, '連結位址' %>
        </div>
    </div>
    <div class="modal-footer">
      <%= button_tag(type: 'submit', class: "waves-effect waves-green btn green", data: {disable_with: '<i class="fa fa-circle-o-notch fa-spin"></i> 資料處理中'}) do %>
        確認新增
      <% end %>
    </div>
  <% end %>
</div>

<%= content_for :handwrite_js do %>
  <script>
    $(document).ready(function(){
      $('.modal-trigger').leanModal();
    });
  </script>
<% end %>

app/views/prototype/index.html.erb
<!-- menu -->
<div class="odd-menu-item top"><a data-behavior="to-members" class="item top" href="#">WE ARE</a></div>
<div class="odd-menu-item right"><a data-behavior="to-works" class="item right" href="#">WORKS</a></div>
<div class="odd-menu-item bottom"><a data-behavior="to-contact" class="item bottom" href="#">CONTACT</a></div>
<div class="odd-menu-item left"><a data-behavior="to-social" class="item left" href="#">THINKING</a></div>

<div class="close-btn" data-behavior="close-btn"></div>

<!-- main content wrapper -->
<div class="odd-content-wrapper">
  <div class="odd-content-inner">

    <%#
      canvas, 這個 div 把所有畫面包起來，利用控制 canvas 的絕對位置來達到在五個獨立
      頁面中滑動切換的目的。（例如：`top: 100%` 會往下滑）
    %>
    <div class="pages-canvas" data-behavior="canvas">

      <!-- landing page -->
      <section class="landing-page">
        <div class="logo-wrapper">
          <%= image_tag 'site-logo.png', class: 'logo' %>
        </div>
      </section>

      <!-- members page -->
      <section class="members-page">
        <div class="member-content-wrapper">
          <% @members.each do |member| %>
            <div class="content-wrapper">
              <div class="member-avatar">
                <%= render_member_avatar(member) %>
              </div>
              <div class="name">
                <span><%= member.name %></span>
              </div>
              <div class="job-icon">
                <span><%= render_profession_icon(member.profession) %></span>
              </div>
              <div class="work-field">
                <span><%= member.work_field %></span>
              </div>
              <div class="subtitle">
                <span><%= member.message %></span>
              </div>
              <div class="social-links">
                <% member.social_services.each do |service| %>
                  <%= render_member_sns_link(service) %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </section>

      <!-- works page -->
      <section class="works-page">
        <div class="temp">Building...</div>
      </section>

      <!-- contact page -->
      <section class="contact-page">

        <div class="contact-info-wrapper">
          <h2 class="title">CONTACT US</h2>
          <ul>
            <li class="info-item">
              <span class="info-title-col">
                Cell
              </span>
              <span class="content-col">
                +886-910-273-948
              </span>
            </li>
            <li class="info-item">
              <span class="info-title-col">
                Email
              </span>
              <span class="content-col">
                service@oddesign.expert
              </span>
            </li>
            <li class="info-item">
              <span class="info-title-col">
                Time
              </span>
              <span class="content-col">
                Mon-Fri 10:00-20:00
              </span>
            </li>
            <li class="info-item">
              <span class="info-title-col">
                Addr
              </span>
              <span class="content-col">
                台北市松山區民生東路4段56巷3弄11號1樓
              </span>
            </li>
          </ul>
        </div>

        <div class="contact-form-wrapper">
          <h2 class="title">CONTACT FORM</h2>
          <%= form_for @form do |f| %>
            <div class="input-field">
              <%= f.email_field :email, class: 'validate' %>
              <%= f.label :email, 'E-mail' %>
            </div>
            <div class="input-field">
              <%= f.text_field :name, class: 'validate' %>
              <%= f.label :name, 'Name' %>
            </div>
            <div class="input-field">
              <%= select :service_form, :project_type, enum_option_pairs(ServiceForm, :project_type), prompt: '選擇專案類型' %>
              <%= f.label :project_type, 'Project Type' %>
            </div>
            <div class="input-field col">
              <%= select :service_form, :budget_range, enum_option_pairs(ServiceForm, :budget_range), prompt: '選擇預算範圍' %>
              <%= f.label :project_type, 'Budget Range' %>
            </div>
            <div class="input-field">
              <%= f.text_area :description, class: 'materialize-textarea' %>
              <%= f.label :description, 'Description' %>
            </div>
            <button type='submit' class="submit-btn waves-effect waves-dark btn">SUBMIT</button>
          <% end %>
        </div>
      </section>

      <!-- social page -->
      <section class="social-page">
        <div class="temp">Building...</div>
      </section>
    </div>

  </div>
</div>

<%= content_for :handwrite_js do %>
  <script>
    $(document).ready(new OddDesign.CanvasController);
  </script>
<% end %>